---
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: password
    ports:
      - ${PGPORT:-5432}:5432
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: password
    ports:
      - ${MYSQL_PORT:-3306}:3306
